import React from 'react';
import Layout from '../components/layout';
import CompliantLinkSidebar from '../components/compliantLinkSidebar';

function TermsOfUse() {
  return (
    <Layout>
      <section>
        <div className="container mx-auto px-4 my-8 md:my-16 grid grid-cols-12 md:gap-x-12 compliance-page">
          <div className="hidden md:block col-span-12 md:col-start-1 md:col-span-2 text-sm">
            <CompliantLinkSidebar />
          </div>
          <div className="col-span-12 md:col-start-3 md:col-span-8 leading-loose text-lt-dark-700 divide-y divide-lt-dark-100 compliance-body">
            <h1 className="font-bold text-4xl mb-4 pb-4 text-lt-dark-900">Terms Of Use</h1>
            <div className="py-8">
              <p>The terms and conditions set forth below (the “terms”) govern your use of this site on the World Wide Web. These terms are a legal contract between you and LeadsTunnel (“we” or “us”) and govern your access to, and use of the LeadsTunnel website located at LeadsTunnel (the “site”) and the services provided on this site. If you do not agree with any of these terms, please do not access or otherwise use this site and/or the services, or any information contained on the site. Your use of this site and/or the services on this site shall be deemed to be your agreement to abide by each of the terms set forth below. LeadsTunnel may make changes to the services offered on this site, at any time without notice, and LeadsTunnel can change these terms at any time without notice by posting updated terms of use on the site. Your continued use of the site after such changes have been posted means that you agree to the new terms, even if you have not reviewed the changes. Therefore, you should check the terms of use posted on the site periodically for updates and changes.</p>
            </div>
            <div className="py-8">
              <h2 className="font-bold text-lg mb-2">Cancellations</h2>
              <h3 className="font-bold">How Cancellations Work</h3>
              <p>LeadsTunnel is a subscription-based software. You are free to cancel your LeadsTunnel subscription at any time by simply contacting support at <a className="text-lt-blue-500 underline" href="mailto:support@leadstunnel.com">support@leadstunnel.com</a>. You will still have access to LeadsTunnel through to the end of your current billing cycle. Please note that your subscription fee will not be prorated and there will not be any refunds or partial refunds for your LeadsTunnel membership.</p>
              <h3 className="font-bold">Free Trials</h3>
              <p>Your LeadsTunnel membership may start with a 7-day free trial. Once your free trial period is over, we will automatically bill your monthly subscription with the credit card on file. If you cancel your subscription before your trial period ends, you will not be billed and you will no longer have access to any features of your LeadsTunnel account.</p>
              <h3 className="font-bold">For Monthly-Subscription Plan</h3>
              <p>If you decide to cancel your monthly LeadsTunnel membership, you will not be billed in the subsequent months. If you are cancelling prior to the end of your monthly billing cycle, you will still have access to LeadsTunnel until the end of your current month’s billing cycle. There is no grace period to cancel your monthly membership and there is no refund or partial refund of your current month subscription.</p>
              <p>It would be very helpful to us if you’d also tell us why you’re requesting a cancellation. This is NOT required, and we won’t use this information to try and “sell” you something else. But we do take feedback seriously, and it really does help us make better products and improve our sales process. We want every customer to be satisfied.</p>
            </div>
            <div className="py-8">
              <h2 className="font-bold text-lg mb-2">General Use Terms</h2>
              <p>LeadsTunnel provides content and other services through the Site. All information, documents, products and services provided on and through the Site, including content, trademarks, logos, graphics and images (together, the “Materials”) are provided to you by LeadsTunnel and are the copyrighted work of LeadsTunnel or LeadsTunnel’s licensors or contributors. LeadsTunnel grants you a limited, personal, non-exclusive and non-transferable license to use the Materials and use the services and the Site solely for your personal use or internal business use. You agree that you will only use this Site and the services for lawful uses.</p>
              <p>You acknowledge and agree that you have no right to modify, edit, copy, reproduce, create derivative works of, alter, enhance or in any way exploit any of the Materials in any manner. This limited license terminates automatically, without notice to you, if you breach any of these Terms. Upon termination of this limited license, you agree to immediately destroy any downloaded or printed Materials. Except as stated herein, you acknowledge that you have no right, title or interest in or to the Site or any Materials on any legal basis.</p>
              <p>You are prohibited from taking any action to circumvent or attempt to circumvent the security and access control provisions of the Site and the Services. Such prohibited conduct includes, without limitation, any efforts to (a) log in to an account with a password not assigned to you, (b) access personally identifiable information not intended for you, (c) test the security measures on the Site and/or attempt to identify system vulnerabilities, (d) impersonate any other user of the Site and/or the Services or forge any of the header information in any posting or tamper with the TCP/IP packet header, (d) modify, reverse engineer, disassemble, decompile or otherwise attempt or allow others to attempt to discover the underlying computer code for the Site and/or the Services, or (f) overwhelm or disable the Site or the Services or interfere with the access and use of the Site and/or the Services by any other user.</p>
              <p>If LeadsTunnel becomes aware of any of the foregoing activities, LeadsTunnel  may investigate and may respond, and when appropriate, LeadsTunnel may work with law enforcement authorities in such investigations and for the purpose of prosecuting offenders.</p>
              <p>Your continued use of the Site and the Services is expressly conditioned on your compliance with the preceding prohibitions and with the obligations and restrictions. Without limiting the generality of foregoing, you acknowledge that LeadsTunnel expressly prohibits and you agree not to:</p>
              <p>Post any false or inaccurate Submissions (defined below) or information;</p>
              <p>Use the Services and/or the Site to violate any applicable law or regulation, including, without limitation, the infringement of any copyright, trademark, trade secret or other intellectual property right of others, or violate the privacy or publicity rights of any other person.</p>
              <p>Post any Submission or information that is abusive, defamatory, discriminatory, hateful, obscene, vulgar, sexually-orientated, threatening, or otherwise objectionable.</p>
              <p>Harass, stalk, or otherwise subject any other user of the Site and/or Services to unwanted and/or inappropriate contact.</p>
              <p>Make any changes, additions and/or deletions to any Submissions posted by any user with out the express written authorization of such other user.</p>
              <p>Take any action that imposes an unreasonable or disproportionately large burden on the Site’s infrastructure.</p>
              <p>Include any hyperlinks or any misleading, irrelevant and/or hidden keywords in any Submissions posted by you.</p>
              <p>Frame or link to the Site or any of the content or information available from the Site, unless LeadsTunnel expressly consents to such linking and/or framing.</p>
              <p>Intentionally expose the Site and/or Service to any computer virus or any other program or code intended to disrupt or disable to operations of the Site and/or Service.</p>
              <p>Use any robot, spider or other program or device to retrieve or index any portion of the LeadsTunnel Site; Harvest or otherwise collect information about other users for any purpose other than use of the Site and/or Services as expressly permitted herein.</p>
              <p>The foregoing list of prohibitions is illustrative and is not intended to be complete or exclusive. LeadsTunnel reserves the right to terminate our relationship with you under these Terms and prohibit your access to the Site and/or Services or to edit, remove or close any Submission or thread for any reason.</p>
              <p>The foregoing prohibitions do not impose on LeadsTunnel, and LeadsTunnel does not assume, any obligation to monitor or remove any Submissions or other information or communication submitted by you or any other member. You hereby acknowledge and agree that there is the chance that you may be exposed to content that may be offensive or objectionable to you. You hereby acknowledge and agree that all submissions submitted by you or any other member express the views of the author, and LeadsTunnel will not be held responsible for or liable for the content in such submissions. Your access to the Site and Services is undertaken at you own risk and LeadsTunnel is not responsible for any offensive or otherwise objectionable materials that may be posted by any third party.</p>
              <h3 className="font-bold">Password Restricted Areas of the Site</h3>
              <p>Certain areas of the Site are password-restricted to authorized users who become members (“Restricted Areas”) or who purchase upgraded areas of the Site. If you are an authorized member of the Restricted Areas, you are responsible for maintaining the confidentiality of your password and account, and agree to notify LeadsTunnel if your password is lost, stolen, or disclosed to an unauthorized third party, or otherwise may have been compromised.</p>
              <p>You are responsible for activities that occur under your account. You agree to immediately notify LeadsTunnel of any unauthorized use of your account or any other breach of security in relation to the Site known to you. You have full 90 day access to your training upon the first day of your purchase.</p>
              <h3 className="font-bold">Pricing and Payments</h3>
              <p>You will pay all fees or charges to your account based on LeadsTunnel’s fees, charges, and billing terms. You may be required to provide LeadsTunnel with a valid credit card as a condition to signing up for an account. You are responsible for paying any taxes that may apply. If you do not pay on time or if LeadsTunnel cannot charge you or your credit card for any reason, LeadsTunnel reserves the right to either suspend or terminate your access to the Site and/or the services and account and terminate these Terms. If you have a balance due on any account, you agree that LeadsTunnel may charge such unpaid fees to your credit card or otherwise bill you for such unpaid fees.</p>
            </div>
            <div className="py-8">
              <h2 className="font-bold text-lg mb-2">Privacy Policy</h2>
              <p>Your use of the Site is governed by the LeadsTunnel Privacy Policy, which is available at Privacy Policy.</p>
              <h3 className="font-bold">Third Party Content</h3>
              <p>Certain information and content may be provided by third parties to LeadsTunnel (“Third Party Content”). The Third Party Content is, in each case, the copyrighted work of the creator/licensor, LeadsTunnel, and iPro Academy, LLC.</p>
              <p>You agree to only display the Third Party Content on your personal computer solely for your personal or internal business use. You acknowledge and agree that you have no right to download, cache, reproduce, modify, display (except as set forth in this paragraph), edit, alter or enhance any of the Third Party Content in any manner. LeadsTunnel Disclaims all express, implied and statutory warranties and conditions with regard to third party content, including, but not limited to, all implied warranties of merchantability, fitness for a particular purpose and non-infringement.</p>
              <h3 className="font-bold">Submissions</h3>
              <p>Subject to the terms and conditions of the LeadsTunnel Privacy Policy (as described above) when you submit data and/or post communications on the Site (collectively “Submissions”), you grant to LeadsTunnel and iPro Academy, LLC, an irrevocable, perpetual, royalty-free, worldwide right (including moral right) and license to use, reproduce, modify, display, distribute and create derivative works of Submissions, in whole or in part, and to incorporate Submissions into other works in any media and utilizing any technology now known or later developed. You warrant that you have all rights, and no third party has retained any such rights, (including moral rights) in and to Submissions.</p>
              <h3 className="font-bold">Links to Third Party Sites</h3>
              <p>This Site may be linked to other sites that are not LeadsTunnel Sites. LeadsTunnel is providing these links to you only as a convenience, and LeadsTunnel is not responsible for the content or links displayed on such sites.</p>
              <h3 className="font-bold">Unauthorized Activities</h3>
              <p>Unauthorized use of any Materials or Third Party Content contained on this Site may violate certain laws and regulations. You shall indemnify and hold LeadsTunnel and its officers, directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all costs, damages, liabilities, and expenses (including attorneys’ fees) that LeadsTunnel or any other indemnified party suffers in relation to, arising from, or for the purpose of avoiding, any claim or demand from a third party in the vent that your use of the Site or the use of the Site by any person using your user name and/or password violates any applicable law or regulation, or the rights of any third party.</p>
              <h3 className="font-bold">Trademarks</h3>
              <p>LeadsTunnel are trademarks of iPro Academy, LLC. in the United States. All other trademarks, names and logos on this Site are the property of their respective owners.</p>
              <h3 className="font-bold">Copyright Notice</h3>
              <p>All information and screens appearing on this Site including documents, services, site design, text, graphics, logos, images and icons, as well as the selection and arrangement thereof, are the sole property of LeadsTunnel and iPro Academy, LLC, unless otherwise specified. All rights not expressly granted herein are reserved. Except as otherwise required by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner.</p>
              <h3 className="font-bold">Disclaimer of Warranties</h3>
              <p>Your use of this Site, the materials and/or the services is at your own risk and you assume all risks of using this Site, the materials and/or the services. Neither the materials nor the third party content have been verified or authenticated in whole or in part by LeadsTunnel, and they may not be current or may include inaccuracies or typographical errors. LeadsTunnel does not warrant the accuracy or timeliness of the materials or the third party content contained on this Site. LeadsTunnel shall have no liability for materials and/or third party content that is not current or for any errors or omissions in the materials and/or the third party content, whether provided by LeadsTunnel or our licensors. LeadsTunnel does not guarantee that you will achieve any economic return or benefit from the use of the materials. LeadsTunnel, for itself and its licensors, makes no express, implied or statutory representations, warranties, or guarantees in connection with the Site, the services or any materials or third party content, relating to the quality, suitability, truth, accuracy, currency or completeness of any information or material contained on the Site, including without limitation, the materials and the third party content. Unless otherwise explicitly stated, to the maximum extent permitted by applicable law, the Site, the services, the Materials, third party content, and any information or material contained on the site is provided to you on an “as is,” “as available” and “where-is” basis with no warranty of any kind and LeadsTunnel disclaims and excludes any and all implied warranties, including any implied warranty of merchantability, fitness for a particular purpose, or non-infringement of third party rights.</p>
              <h3 className="font-bold">Limitation of Liability</h3>
              <p>LeadsTunnel’s aggregate liability to you or any third party for any damages resulting from your displaying, copying, or downloading any material on the site or reliance on the information and/or material presented on the site shall not exceed fifty dollars ($50.00). in no event shall LeadsTunnel be liable to you or any third party for any indirect, extraordinary, exemplary, punitive, special, incidental, or consequential damages (including loss of data, revenue, profits, use or other economic advantage) however arising, even if LeadsTunnel has been advised of the possibility of such damage.</p>
              <h3 className="font-bold">Local Laws & Export Control</h3>
              <p>LeadsTunnel controls and operates this Site from its headquarters in the United States of America and the Materials may not be appropriate or available for use in other locations. If you use this Site outside the United States of America, you are responsible for compliance with all applicable local laws.</p>
              <h3 className="font-bold">General</h3>
              <p>If you violate these Terms, LeadsTunnel may terminate your access to the Site or Restricted Areas without notice. LeadsTunnel prefers to advise you of your inappropriate behavior and recommend any necessary corrective action. However, certain violations of these Terms, as determined by LeadsTunnel, will result in immediate termination of your access to the Site or Restricted Areas. LeadsTunnel has the right to terminate any password-restricted account for any reason. Maryland law and controlling U.S. federal law, without regard to the choice or conflicts of law provisions, will govern these Terms. Any disputes relating to these Terms or the Site will be heard in the courts located in Maryland. If any of these Terms is found to be inconsistent with applicable to law, then such Term shall be interpreted to reflect the intentions of the parties, and no other Terms will be modified. LeadsTunnel’s failure to enforce any of these Terms is not a waiver of such Terms. The Terms are the entire agreement between you and LeadsTunnel and supersede all prior or contemporaneous agreements and understandings between you and LeadsTunnel with respect to the subject matter hereof. These Terms may not be modified except pursuant to a written amendment that is executed by an officer of LeadsTunnel.</p>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  )
}

export default TermsOfUse
